#!/bin/bash

set -e

##################################################################
#   stax - for aws ec2 - https://github.com/philcryer/stax
#   https://github.com/philcryer/stax/blob/master/LICENSE
##################################################################

SCRIPT_PATH=$( cd $(dirname $0) ; pwd -P )
STACK_DISCOVERY_URL=$(curl -s https://discovery.etcd.io/new)
STACK_SSHFROM="$(curl -s http://ipecho.net/plain)/32"

stax-colors(){
  green=$(tput setaf 2)
  yellow=$(tput setaf 3)
  blue=$(tput setaf 4)
  purple=$(tput setaf 5)
  cyan=$(tput setaf 6)
  white=$(tput setaf 7)
  reset=$(tput sgr0)
}

stax-usage(){
echo "Usage: stax <options> command"

echo; echo "Commands:"
echo "  dryrun        Don't do anything, just show what would be done"
echo "  create        Create new stax"
echo "  describe      Describe existing stax"
echo "  get-ip        Get the public, or elastic IP of stax"
echo "  delete        Delete existing stax"

echo; echo "For more help, check the docs; https://github.com/philcryer/stax"
exit 1
}

[ $# -gt 0 ] || stax-usage

stax-logo(){
  echo "${green}     _             "
  echo "    | | ${yellow}for aws ec2${green}"
  echo " ___| |_ __ ___  __"
  echo '/ __| __/ _` \ \/ /'
  echo '\__ \ || (_| |>  < '
  echo "|___/\__\__,_/_/\_\ ${reset}"
  echo
}

stax-preflight(){
  # awscli check
  which aws > /dev/null 2>&1 || { echo "awscli is not installed. Aborting."; exit 1; }
  echo "${yellow}[  ${green}ok${yellow}  ]${reset} awscli installed"
  # awscli config check
  if [ ! -f ${HOME}/.aws/config ]; then
     echo "awscli not configured, run 'aws configure'. Aborting."; exit 1
  fi
  echo "${yellow}[  ${green}ok${yellow}  ]${reset} awscli configured"
  # stax dot dir check
  if [ ! -d ~/.stax ]; then
    mkdir ~/.stax
  fi
  echo "${yellow}[  ${green}ok${yellow}  ]${reset} stax config dir available"
  # stax config check
  if [ ! -f ~/.stax/config ]; then
    cp config/stax-config ${HOME}/.stax/config
  fi
  echo "${yellow}[  ${green}ok${yellow}  ]${reset} stax config file available"
  # awscli key check
#  aws ec2 describe-key-pairs --key-names $STACK_KEY_PAIR --region $STACK_REGION > /dev/null 2>&1 || { echo "Keypair $STACK_KEY_PAIR does not exit."; exit 1; }
}

stax-config(){
  source ${HOME}/.stax/config
}

stax-summary(){
  echo "${yellow}[ ${cyan}----${yellow} ]${reset} stax summary"
  echo "${yellow}[ ${blue}info${yellow} ]${reset} stax name: $STACK_NAME"
  echo "${yellow}[ ${blue}info${yellow} ]${reset} instance type: $STACK_INSTANCE_TYPE"
  echo "${yellow}[ ${blue}info${yellow} ]${reset} cluster size: $STACK_CLUSTER_SIZE nodes"
  echo "${yellow}[ ${blue}info${yellow} ]${reset} discovery url: $STACK_DISCOVERY_URL"
  echo "${yellow}[ ${blue}info${yellow} ]${reset} ec2 key pair: $STACK_KEY_PAIR"
  echo "${yellow}[ ${blue}info${yellow} ]${reset} ssh from ip: $STACK_SSHFROM"
}

stax-create(){
  echo $STACK_NAME > ~/.stax/stack_name
  echo "${yellow}[ ${cyan}----${yellow} ]${reset} creating $STACK_CLUSTER_SIZE nodes - $STACK_NAME"
  aws --no-verify-ssl --color on cloudformation create-stack \
    --region $STACK_REGION \
    --stack-name $STACK_NAME \
    --template-body file://$SCRIPT_PATH/templates/cloudformation-template-$COREOS_CHANNEL.json \
    --parameters \
      "ParameterKey=InstanceType,ParameterValue=$STACK_INSTANCE_TYPE,UsePreviousValue=false" \
      "ParameterKey=ClusterSize,ParameterValue=$STACK_CLUSTER_SIZE,UsePreviousValue=false" \
      "ParameterKey=DiscoveryURL,ParameterValue=$STACK_DISCOVERY_URL,UsePreviousValue=false" \
      "ParameterKey=AdvertisedIPAddress,ParameterValue=private,UsePreviousValue=false" \
      "ParameterKey=AllowSSHFrom,ParameterValue=$STACK_SSHFROM,UsePreviousValue=false" \
      "ParameterKey=KeyPair,ParameterValue=$STACK_KEY_PAIR,UsePreviousValue=false"
}

stax-describe(){
  aws cloudformation describe-stacks --stack-name $STACK_NAME --output table
  exit 0
}

stax-get-ip(){
  bar
}

stax-delete(){
  # verify stack exists, then delete
  aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null && aws cloudformation delete-stack  --stack-name $STACK_NAME 
  rm $HOME/.stax/stack_name
}

clear
stax-colors
stax-logo
stax-preflight
stax-config
if [ -f $HOME/.stax/stack_name ]; then
  STACK_NAME=`cat $HOME/.stax/stack_name`
fi
if [ ! -f $HOME/.stax/stack_name ]; then
  STACK_NAME="$STACK_PRE_NAME-$RANDOM"
  echo $STACK_NAME > $HOME/.stax/stack_name
fi
stax-summary

if [[ "$1" == "dryrun" ]]; then
 echo "${yellow}[ ${cyan}----${yellow} ]${reset} dryrun only, exiting"
 exit 0
fi

if [[ "$1" == "create" ]]; then
  stax-create
  stax-describe
  echo "${yellow}[ ${cyan}----${yellow} ]${reset} creation complete"
fi

if [[ "$1" == "describe" ]]; then
  if [ -f $HOME/.stax/stack_name ]; then
    echo "${yellow}[ ${cyan}----${yellow} ]${reset} describe $STACK_NAME"
    stax-describe
  else
    echo "${yellow}[ ${red}ERRR${yellow} ]${reset} no stax defined"
  fi
fi

if [[ "$1" == "delete" ]]; then
  if [ -f $HOME/.stax/stack_name ]; then
    echo "${yellow}[ ${cyan}----${yellow} ]${reset} will delete $STACK_NAME"
    stax-delete
    echo "${yellow}[ ${cyan}----${yellow} ]${reset} stax $STACK_NAME deleted"
  else
    echo "${yellow}[ ${cyan}----${yellow} ]${reset} could not delete $STACK_NAME, check name"
    exit 1
  fi
fi

exit 0
