# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
[ -z "$PS1" ] && return
PATH=$PATH:~
cat motd
echo -n "System    "
echo `cat /etc/issue.net | head -n1`
echo ""
