#!/bin/bash

echo "${yellow}[ ${cyan}----${yellow} ]${reset}    running CoreOS hosts: "
echo "{"
ssh -i ~/.ssh/STAX_KEY.pem -l core -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "LogLevel=quiet" `python -c "import random, sys; print random.choice(open(sys.argv[1]).readlines())," docker_hosts` 'fleetctl list-machines'
echo "}"
echo "${yellow}[ ${cyan}----${yellow} ]${reset}    running Docker Units: "
echo "{"
ssh -i ~/.ssh/STAX_KEY.pem -l core -o "UserKnownHostsFile=/dev/null" -o "LogLevel=quiet" -o "StrictHostKeyChecking no" `python -c "import random, sys; print random.choice(open(sys.argv[1]).readlines())," docker_hosts` 'fleetctl list-units'
echo "}"
echo "${yellow}[ ${cyan}----${yellow} ]${reset}    loaded Unit Files on CoreOS hosts: "
echo "{"
ssh -i ~/.ssh/STAX_KEY.pem -l core -o "UserKnownHostsFile=/dev/null" -o "LogLevel=quiet" -o "StrictHostKeyChecking no" `python -c "import random, sys; print random.choice(open(sys.argv[1]).readlines())," docker_hosts` 'fleetctl list-unit-files'
echo "}"
